# Generated by Django 3.0.8 on 2020-07-18 08:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название темы', max_length=2000, verbose_name='Название темы')),
                ('active', models.BooleanField(default=True, help_text='Активна ли эта тема на сайте', verbose_name='Активация')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Темы',
                'db_table': 'topics',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(blank=True, max_length=2000, null=True)),
                ('text', ckeditor.fields.RichTextField(help_text='Отредактируйте текст, так как Вы хотите что бы он выглядел на сайте', verbose_name='Текс для поста')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения фаила')),
                ('active', models.BooleanField(default=True, help_text='Активен ли этот фаил на сайте', verbose_name='Активация')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Topic')),
            ],
            options={
                'verbose_name': 'Посты',
                'db_table': 'posts',
                'ordering': ('last_update',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Фаил', help_text='Название фаила не обязательно', max_length=2000, null=True, verbose_name='Название фаила')),
                ('file_link', models.FileField(help_text='Выберите нужный фаил для поста', upload_to='upload_file/', verbose_name='Загрузите фаил')),
                ('active', models.BooleanField(default=True, help_text='Активен ли этот фаил на сайте', verbose_name='Активация')),
                ('post', models.ForeignKey(help_text='К какому посту будет прикреплен фаил', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='posts.Post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фаилы',
                'db_table': 'files',
                'ordering': ('id',),
            },
        ),
    ]
