# Generated by Django 3.0.8 on 2020-07-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200719_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Foo', unique=True),
        ),
    ]
