# Generated by Django 3.0.8 on 2020-07-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200727_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name_post',
            new_name='name',
        ),
    ]
