# Generated by Django 4.2.4 on 2023-08-10 06:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200801_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Відкерактуйте текст, так Ви бажаєте щоб він виглядав на сайті', verbose_name='Текс для посту'),
        ),
    ]
